version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./src:/src
    environment:
       PROJECT_NAME: test

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    env_file:
      .env
    ports:
      - 13306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin-session:/sessions

