version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./app:/app
    environment:
      PROJECT_NAME: test

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "4040:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: lolcalhost:3306
      PMA_USER: root
      PMA_PASSWORD: root
    volumes:
      - ./phpmyadmin-session:/sessions

